/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */

import org.scalatest._
import matchers.must.Matchers
import org.scalatest.funspec.AnyFunSpec

class LibrarySuite extends AnyFunSpec with Matchers {
  describe("s") {
    it("") {
      1 mustEqual 1
    }
  }
}
